In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("../data/customer_churn.db")

In [3]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

             name
0  customer_churn

In [4]:
conn = sqlite3.connect("../data/customer_churn.db")

In [5]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

             name
0  customer_churn

In [6]:
query = """
SELECT COUNT(*) AS Total_Customers
FROM customer_churn;
"""

pd.read_sql(query, conn)

   Total_Customers
0             7043

In [7]:
query = """
SELECT Contract,
AVG(Monthly_Charges) AS AvgCharge
FROM customer_churn
GROUP BY Contract;
"""

pd.read_sql(query, conn)

         Contract  AvgCharge
0  Month-to-month  66.398490
1        One year  65.048608
2        Two year  60.770413

In [8]:
query = """
SELECT CustomerID,
Total_Charges
FROM customer_churn
ORDER BY Total_Charges DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

   CustomerID  Total_Charges
0  2889-FPWRM        8684.80
1  7569-NMZYQ        8672.45
2  9739-JLPQJ        8670.10
3  9788-HNGUT        8594.40
4  8879-XUAHX        8564.75
5  9924-JPRMC        8547.15
6  0675-NCDYU        8543.25
7  6650-BWFRT        8529.50
8  0164-APGRB        8496.70
9  1488-PBLJN        8477.70

In [9]:
query = """
SELECT CustomerID,
Total_Charges
FROM customer_churn
ORDER BY Total_Charges DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

   CustomerID  Total_Charges
0  2889-FPWRM        8684.80
1  7569-NMZYQ        8672.45
2  9739-JLPQJ        8670.10
3  9788-HNGUT        8594.40
4  8879-XUAHX        8564.75
5  9924-JPRMC        8547.15
6  0675-NCDYU        8543.25
7  6650-BWFRT        8529.50
8  0164-APGRB        8496.70
9  1488-PBLJN        8477.70

In [10]:
query = """
SELECT Payment_Method,
COUNT(*) AS Churned_Customers
FROM customer_churn
WHERE Churn_Label='Yes'
GROUP BY Payment_Method
ORDER BY Churned_Customers DESC;
"""

pd.read_sql(query, conn)

              Payment_Method  Churned_Customers
0           Electronic check               1071
1               Mailed check                308
2  Bank transfer (automatic)                258
3    Credit card (automatic)                232

In [11]:
conn.close()